spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/pin_desk
    username: pin
    password: pin
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true

logging:
  level:
    org.springframework.boot.context.config: DEBUG
    org.flywaydb: INFO

app:
  jwt:
    secret: "CHANGE_ME_TO_LONG_RANDOM_SECRET_32+_CHARS"
    ttlMinutes: 120